Repository googleinterns/step73-2020, pull requests merged in 2020-07, with the labels that each got.

#10 Add functionality for /create-person servlet, which can create a person and save it in the database.
  server/pom.xml
  server/src/main/java/com/google/coffeehouse/common/Person.java
  server/src/main/java/com/google/coffeehouse/common/Saveable.java
  server/src/main/java/com/google/coffeehouse/servlets/CreatePersonServlet.java
  server/src/main/java/com/google/coffeehouse/util/IdentifierGenerator.java
  server/src/main/java/com/google/coffeehouse/util/UuidWrapper.java
  server/src/test/java/com/google/coffeehouse/common/PersonTest.java
  server/src/test/java/com/google/coffeehouse/servlets/CreatePersonServletTest.java
Labels: mvp

#8 Create Storage Handler
  server/pom.xml
  server/src/main/java/com/google/coffeehouse/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/StorageHandlerHelper.java
  server/src/main/java/com/google/coffeehouse/StorageHandlerSetup.java
  server/src/test/java/com/google/coffeehouse/StorageHandlerTest.java
Labels: mvp

#23 Modify storage handler
  server/src/main/java/com/google/coffeehouse/common/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/common/StorageHandlerHelper.java
  server/src/main/java/com/google/coffeehouse/common/StorageHandlerSetup.java
  server/src/test/java/com/google/coffeehouse/common/StorageHandlerTest.java
Labels: mvp

#30 Configure communication between frontend and server in development and when deployed.
  .gitignore
  README.md
  dispatch.yaml
  frontend/README.md
  frontend/app.yaml
  frontend/configs/webpack/dev.js
  frontend/express.js
  frontend/package-lock.json
  frontend/package.json
  run-dev.sh
  server/README.md
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/CreatePersonServlet.java
  server/src/main/webapp/WEB-INF/appengine-web.xml
  server/src/main/webapp/index.html
Labels: mvp

#28 Update Storage Handler with object creation and new functions
  server/src/main/java/com/google/coffeehouse/common/MembershipConstants.java
  server/src/main/java/com/google/coffeehouse/common/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/common/StorageHandlerHelper.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerApi.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerCommonMutations.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerHelper.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerSetup.java
  server/src/test/java/com/google/coffeehouse/common/StorageHandlerTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerHelperTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTestHelper.java
Labels: mvp

#40 Fix bug where sometimes the environment variable would not be set.
  run-dev.sh
Labels: bug

#43 Refactor Person to allow setting of userId in builder directly.
  server/src/main/java/com/google/coffeehouse/common/Person.java
  server/src/main/java/com/google/coffeehouse/servlets/CreatePersonServlet.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/test/java/com/google/coffeehouse/common/PersonTest.java
  server/src/test/java/com/google/coffeehouse/servlets/CreatePersonServletTest.java
Labels: mvp

#51 Allow direct setting of Club ID and Book ID in builder.
  server/src/main/java/com/google/coffeehouse/common/Book.java
  server/src/main/java/com/google/coffeehouse/common/Club.java
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerApi.java
  server/src/test/java/com/google/coffeehouse/common/BookTest.java
  server/src/test/java/com/google/coffeehouse/common/ClubTest.java
  server/src/test/java/com/google/coffeehouse/servlets/CreateClubServletTest.java
Labels: mvp

#39 Added authentication through oauth/openid.
  .gitignore
  frontend/configs/jest.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App.tsx
  frontend/src/components/contexts/contexts.ts
  frontend/src/components/contexts/default_services.ts
  frontend/src/components/pages/login/Login.tsx
  frontend/src/components/pages/profile/Profile.tsx
  frontend/src/components/pages/your_clubs/YourClubs.tsx
  frontend/src/components/sign_in/GoogleSignInButton.spec.tsx
  frontend/src/components/sign_in/GoogleSignInButton.tsx
  frontend/src/index.html.ejs
  frontend/src/services/authentication_handler_service/authentication_constants.ts
  frontend/src/services/authentication_handler_service/authentication_handler_service.spec.ts
  frontend/src/services/authentication_handler_service/authentication_handler_service.ts
  frontend/src/services/backend/authentication_backend.ts
  frontend/src/services/backend/profile_backend.ts
  frontend/src/services/backend_service_interface/backend_service_interface.ts
  frontend/tsconfig.json
  server/pom.xml
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/CreatePersonServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/RetrieveTokenServlet.java
  server/src/main/java/com/google/coffeehouse/util/AuthenticationConstants.java
  server/src/test/java/com/google/coffeehouse/servlets/RetrieveTokenServletTest.java
  server/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: mvp

#73 Edit /get-profile servlet with updated doc comments
  server/src/main/java/com/google/coffeehouse/servlets/GetProfileServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/GetProfileServletTest.java
Labels: mvp

#70 Add /api/update-club servlet to allow club owners to update their club.
  server/src/main/java/com/google/coffeehouse/servlets/RetrieveTokenServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/UpdateClubServlet.java
  server/src/main/java/com/google/coffeehouse/util/AuthenticationHelper.java
  server/src/test/java/com/google/coffeehouse/servlets/RetrieveTokenServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/UpdateClubServletTest.java
Labels: high priority, mvp

#72 Add /leave-club functionality
  server/src/main/java/com/google/coffeehouse/servlets/LeaveClubServlet.java
  server/src/main/java/com/google/coffeehouse/util/AuthenticationHelper.java
  server/src/test/java/com/google/coffeehouse/servlets/LeaveClubServletTest.java
Labels: high priority, mvp

#69 Add /join-club functionality
  server/src/main/java/com/google/coffeehouse/servlets/GetProfileServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/JoinClubServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/GetProfileServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/JoinClubServletTest.java
Labels: high priority, mvp

#75 Integrate backend to frontend for Login, Sign Out, Customized components functionality.
  frontend/src/components/App.tsx
  frontend/src/components/appbar/AppBar.tsx
  frontend/src/components/contexts/contexts.ts
  frontend/src/components/contexts/default_services.ts
  frontend/src/components/drawer/Drawer.tsx
  frontend/src/components/pages/login/Login.tsx
  frontend/src/services/authentication_handler_service/authentication_handler_service.ts
  frontend/src/services/login_status_handler_service/login_status_handler_service.ts
Labels: high priority

#76 Add /api/list-clubs which returns a JSON array of clubs that the user is (not) a member of.
  server/src/main/java/com/google/coffeehouse/servlets/ListClubsServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/ListClubsServletTest.java
Labels: high priority, mvp

#85 Create person in Spanner if their profile does not exist.
  frontend/src/components/pages/login/Login.tsx
Labels: high priority, mvp

#71 Add /api/get-club servlet which returns the JSON representation of a club given that club's ID.
  server/src/main/java/com/google/coffeehouse/servlets/GetClubServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/GetClubServletTest.java
Labels: high priority, mvp

#81 Create functionality for adding ownership to a club in the Storage Handler
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerApi.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerCommonMutations.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerHelper.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerHelperTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTestHelper.java
Labels: high priority, mvp

#84 Update /create-club servlet to add ownership to club
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/CreateClubServletTest.java
Labels: high priority, mvp

#86 Create tests to check the creation of objects in the Storage Handler
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerHelperTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTestHelper.java
Labels: high priority, mvp

#83 Replace body in GET requests with URL parameters.
  server/src/main/java/com/google/coffeehouse/servlets/GetProfileServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/ListClubsServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/GetProfileServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/ListClubsServletTest.java
Labels: bug, high priority, mvp

#79 Update /api/update-person to take ID token rather than user ID.
  server/src/main/java/com/google/coffeehouse/servlets/UpdatePersonServlet.java
  server/src/test/java/com/google/coffeehouse/servlets/UpdatePersonServletTest.java
Labels: high priority, mvp

#82 Add ability for Person, Club, and Book objects to invoke .save() method.
  server/src/main/java/com/google/coffeehouse/common/Book.java
  server/src/main/java/com/google/coffeehouse/common/Club.java
  server/src/main/java/com/google/coffeehouse/common/Person.java
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/CreatePersonServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/UpdateClubServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/UpdatePersonServlet.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandlerApi.java
  server/src/test/java/com/google/coffeehouse/common/BookTest.java
  server/src/test/java/com/google/coffeehouse/common/ClubTest.java
  server/src/test/java/com/google/coffeehouse/common/PersonTest.java
  server/src/test/java/com/google/coffeehouse/servlets/CreateClubServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/CreatePersonServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/UpdateClubServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/UpdatePersonServletTest.java
Labels: high priority, mvp

#93 Refactor Storage Handler
  server/src/main/java/com/google/coffeehouse/common/MembershipConstants.java
  server/src/main/java/com/google/coffeehouse/servlets/CreateClubServlet.java
  server/src/main/java/com/google/coffeehouse/servlets/LeaveClubServlet.java
  server/src/main/java/com/google/coffeehouse/storagehandler/StorageHandler.java
  server/src/test/java/com/google/coffeehouse/servlets/CreateClubServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/LeaveClubServletTest.java
  server/src/test/java/com/google/coffeehouse/servlets/ListClubsServletTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerHelperTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTest.java
  server/src/test/java/com/google/coffeehouse/storagehandler/StorageHandlerTestHelper.java
Labels: mid priority, mvp

#95 Rework login to use the Auth2 library
  frontend/src/components/App.tsx
  frontend/src/components/appbar/AppBar.tsx
  frontend/src/components/contexts/contexts.ts
  frontend/src/components/contexts/default_services.ts
  frontend/src/components/drawer/Drawer.tsx
  frontend/src/components/pages/explore/Explore.tsx
  frontend/src/components/pages/explore/ExploreClubList.tsx
  frontend/src/components/pages/login/Login.tsx
  frontend/src/components/pages/profile/Profile.tsx
  frontend/src/components/pages/unloaded/Unloaded.tsx
  frontend/src/components/pages/your_clubs/ClubList.tsx
  frontend/src/components/pages/your_clubs/CreateNewClub.tsx
  frontend/src/components/pages/your_clubs/YourClubs.tsx
  frontend/src/index.html.ejs
  frontend/src/index.tsx
  frontend/src/services/authentication_handler_service/authentication_handler_service.spec.ts
  frontend/src/services/authentication_handler_service/authentication_handler_service.ts
  frontend/src/services/login_status_handler_service/login_status_handler_service.ts
Labels: enhancement, mid priority
